# Change column names for better reproducibility

In [30]:
import pandas as pd


df = pd.read_csv('dataset/yelp_data/yelp_polarity_test.csv')

df.head(10)

,2,"Contrary to other reviews, I have zero complaints about the service or the prices. I have been getting tire service here for the past 5 years now, and compared to my experience with places like Pep Boys, these guys are experienced and know what they're doing. \nAlso, this is one place that I do not feel like I am being taken advantage of, just because of my gender. Other auto mechanics have been notorious for capitalizing on my ignorance of cars, and have sucked my bank account dry. But here, my service and road coverage has all been well explained - and let up to me to decide. \nAnd they just renovated the waiting room. It looks a lot better than it did in previous years."
0,1,Last summer I had an appointment to get new ti...
1,2,"Friendly staff, same starbucks fair you get an..."
2,1,The food is good. Unfortunately the service is...
3,2,Even when we didn't have a car Filene's Baseme...
4,2,"Picture Billy Joel's \""Piano Man\"" DOUBLED mix..."
5,1,Mediocre service. COLD food! Our food waited s...
6,1,Ok! Let me tell you about my bad experience fi...
7,1,I used to love D&B when it first opened in the...
8,2,"Like any Barnes & Noble, it has a nice comfy c..."
9,1,"Meh, I've experienced better is an understatem..."

In [22]:
# Change the column names
old_name1 = df.columns[0]
df.rename(columns={old_name1: 'sentiment'}, inplace=True)

old_name = df.columns[1]

df.rename(columns={old_name: 'text'}, inplace=True)

df.head(10)

   sentiment                                               text
0          2  Been going to Dr. Goldberg for over 10 years. ...
1          1  I don't know what Dr. Goldberg was like before...
2          1  I'm writing this review to give you a heads up...
3          2  All the food is great here. But the best thing...
4          1  Wing sauce is like water. Pretty much a lot of...
5          1  Owning a driving range inside the city limits ...
6          1  This place is absolute garbage...  Half of the...
7          2  Before I finally made it over to this range I ...
8          2  I drove by yesterday to get a sneak peak.  It ...
9          1  After waiting for almost 30 minutes to trade i...

In [23]:
# Convert the sentiment column to 'positive' and 'negative'
df['sentiment'] = df['sentiment'].map({1: 'negative', 2: 'positive'})

In [24]:
df.to_csv('dataset/yelp_data/updated_yelp_polarity_train.csv', index=False)

# Making the Tweet dataset uniform (similar col values to yelp dataset)

In [25]:
import pandas as pd


df = pd.read_csv('dataset/tweet_data/tweet_data.csv')

df.head(10)

       textID                                         tweet_text sentiment
0  1956967666  Layin n bed with a headache  ughhhh...waitin o...  negative
1  1956967696                Funeral ceremony...gloomy friday...  negative
2  1956967789               wants to hang out with friends SOON!  positive
3  1956968477  Re-pinging @ghostridah14: why didn't you go to...  negative
4  1956968636               Hmmm. http://www.djhero.com/ is down  negative
5  1956969035            @charviray Charlene my love. I miss you  negative
6  1956969172         @kelcouch I'm sorry  at least it's Friday?  negative
7  1956969531                            Choked on her retainers  negative
8  1956970047  Ugh! I have to beat this stupid song to get to...  negative
9  1956970424  @BrodyJenner if u watch the hills in london u ...  negative

In [26]:
# Change the column names
# Only need to change the second column name - as it was previously named tweet_text
old_name = df.columns[1]

df.rename(columns={old_name: 'text'}, inplace=True)

df.head(10)

       textID                                               text sentiment
0  1956967666  Layin n bed with a headache  ughhhh...waitin o...  negative
1  1956967696                Funeral ceremony...gloomy friday...  negative
2  1956967789               wants to hang out with friends SOON!  positive
3  1956968477  Re-pinging @ghostridah14: why didn't you go to...  negative
4  1956968636               Hmmm. http://www.djhero.com/ is down  negative
5  1956969035            @charviray Charlene my love. I miss you  negative
6  1956969172         @kelcouch I'm sorry  at least it's Friday?  negative
7  1956969531                            Choked on her retainers  negative
8  1956970047  Ugh! I have to beat this stupid song to get to...  negative
9  1956970424  @BrodyJenner if u watch the hills in london u ...  negative

In [27]:
df.to_csv('dataset/tweet_data/updated_tweet_data', index=False)